name: Dev CICD

on:
  workflow_dispatch:

  push:
    branches:
      - 'main'

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'

env:
  ENV: dev

jobs:

  publish-the-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:dev
          build-args: |
            VITE_PUBLIC_URL=${{ secrets.VITE_PUBLIC_URL }}
            VITE_API_URL=${{ secrets.VITE_API_URL }}

  Deploy-to-Kubernetes:
    needs: publish-the-docker-image
    runs-on: ubuntu-latest
    steps:
      -
        name: Install and configure kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          echo "${{ secrets.ELECTED_K8_KUBECONFIG }}" | base64 --decode > kubeconfig.yaml

      -
        name: Deploy to Kubernetes
        run: |
          KUBECONFIG=kubeconfig.yaml kubectl rollout restart deployment/${{ secrets.DEPLOYMENT_NAME }} -n ${{ secrets.NAMESPACE }}
